### ISSUE TITLE
创意中心在引入 Brix Style 后遇到的一些问题以及解决办法

### ISSUE THREAD

**Issue by cyjake** [etaoux/brix#34]
先说明一下创意中心，使用 Rails 开发，样式最初是纯 CSS 写，后来 Rails 有了 Asset Pipeline，改用 SCSS ，使用 KISSY CSS 里的 reset.css 做样式重置，没有栅格，简单写了个 1000px 宽的居中。

起初因为担心 normalize.less 与 reset.css 出入太多，没有使用编译好的 brix.css，而是挑了用得到的部分，一点点放进来。后来发现，除了重置方式的差别之外，form.less 打击面太广，也是一个大问题。标签与头像没有用上，按下不表。
### 问题一：Less 与 SCSS 之分

两周前开始尝试，用了最需要的 grid.less，并改写成 grid.scss。顺便在此详细答 @xthsky 问，为何改写而不直接用，原因如下：
- Rails 默认支持的是这个
- 旧代码全部是 SCSS
- SCSS 的流程控制语法更简洁，mixin 和 include 的用法也更清楚明了

第三点在 grid.scss 中比较明显，代码请看 https://github.com/dotnil/brix-style/blob/master/src/grid.scss ，
对比 Less 版本：https://github.com/etaoux/brix/blob/master/src/style/mixins.less#L184

所以此问题，我的解决办法是用 SCSS 重写。除了流程控制语法差别比较大之外，其他的都比较细微：
- 变量名，Less 用的 @foo，而 SCSS 是 $foo http://sass-lang.com/docs/yardoc/file.SASS_REFERENCE.html#variables_
- 色彩操作函数有不一致处 http://sass-lang.com/docs/yardoc/Sass/Script/Functions.html
- mixin 的声明与使用方式 http://sass-lang.com/docs/yardoc/file.SASS_REFERENCE.html#mixins

不过，新启动的 Rails 项目，不用担心此问题，换 Less 的代价并不大，有现成的 gem 支持，https://github.com/metaskills/less-rails
### reset 与 normalize

然后遇到的就是 Brix Style 自身代码的问题了，normalize 与 reset 的出入，我感受到比较多的就两个：
- ul、ol 没有重置
- p、h[1-6]、pre 等，有 `margin: 1em 0`；

前者，我增加了 .reset 来把它们重置掉，在需要重置的 ul、ol 上加 .reset 就好：

``` scss
ul, ol {
  &.reset {
    margin: 0;
    padding: 0;

    li {
      list-style: none;
      margin: none;
    }
  }
}
```

后者，我挺喜欢这种方式的。这个差别造成的问题自然不少，不过挨个改一下也没那么难。自带的 reset-patch 我并没有用。
### form 太 tnnd 的暴力了

https://github.com/etaoux/brix/blob/master/src/style/forms.less#L73

label、input、legend 有 margin 有 width，让我之前散落各处，并不在 form 中 label、input 全都奇葩了……

所以我直接把它们塞回到 form 里面去 https://github.com/dotnil/brix-style/blob/master/src/form.scss#L42

其他一些与我项目不符的，则在项目样式中重置、补齐。
### button 的不足之处

Rails 项目中，有种按钮是通过 <%= button_to %> 生成的，结构类似这样：

``` erb
<%= button_to '拷贝创意', mitosis_creation_path(:id => creation.id), :class => 'btn', :method => 'post' %>
```

``` html
<form action="/creations/100351/mitosis" class="button_to" method="post">
  <div>
    <input class="btn" type="submit" value="拷贝创意">
    <input name="authenticity_token" type="hidden" value="XLtk0GDl1SEeTXinitnb/9DmaUNHBf7eGoszUlS1NRA=">
  </div>
</form>
```

为什么一个按钮要搞成这样，说来话长，幸运的是，在我的项目里这种 .btn 都只在 .btn-group 里面使用，所以我可以这么搞：

``` scss
.btn-group {
  form, .btn {
    float: left;
  }
  form:first-child {
    .btn {
      border-left-width: 1px;
      @include border-top-left-radius(2px);
      @include border-bottom-left-radius(2px);
    }
  }
  form:last-child {
    .btn {
      @include border-top-right-radius(2px);
      @include border-bottom-right-radius(2px);
    }
  }
}
```

曲线救国吧。

另外，在 button.less 中有一些针对低版本 IE 的 hack，https://github.com/etaoux/brix/blob/master/src/style/buttons.less#L9 ，我在项目中并没能重现这些问题，所以都直接去掉了。或者，注释再详细一点？

还有一些细节问题，我迟些补充吧，光看代码想不起来了……
### EOF

Brix Style 中，还有 avatar、tag、scrollbar 等，这些我都没有使用，不发表意见。
