### ISSUE TITLE
业务子组件库共用CSS如何处理？

### ISSUE THREAD

**Issue by limu** [etaoux/brix#43]
直通车重构的系列组件有一些公用的CSS,内容比较简单.比如：

``` css
.fl{float:left;display:inline;}
.fr{float:right;display:inline;}
.mt15{margin-top:15px;}
.mb15{margin-bottom:15px;}
.ml15{margin-left:15px;}
.tl{text-align:left;}
.tr{text-align:right;}
.tc{text-align:center;}
.none{display:none;}
```

我们希望每个组件可以单独共享，那这类css如何做共享？冲突如何处理？写法是否该有些约定？
